# Generated by Django 5.1.7 on 2025-04-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('ordering', 'Ordering'), ('shipping', 'Shipping'), ('returns', 'Returns'), ('products', 'Products'), ('payments', 'Payments'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
