# Generated by Django 5.1.7 on 2025-05-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_country'),
    ]

    operations = []